//
// Created by seba on 2/18/21.
//

#ifndef TUHH_INTAIRNET_MC_SOTDMA_BCLINKMANAGER_HPP
#define TUHH_INTAIRNET_MC_SOTDMA_BCLINKMANAGER_HPP


class BCLinkManager {

};


#endif //TUHH_INTAIRNET_MC_SOTDMA_BCLINKMANAGER_HPP
